import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Glossary</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Typography variant="h1">Welcome to Glossary!</Typography>

        <Typography variant="h5">
          See the&nbsp;
          <Link href="glossary">
            <a>list of terms</a>
          </Link>
          .
        </Typography>
      </main>
    </div>
  );
};

export default Home;
